# Copyright (c) 2019, G.A. vd. Hoorn
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author G.A. vd. Hoorn

# List of IO types and their IDs.

uint8 DI  =  1
uint8 DO  =  2
uint8 RI  =  8
uint8 RO  =  9
uint8 SI  = 11
uint8 SO  = 12
uint8 WI  = 16
uint8 WO  = 17
uint8 UI  = 20
uint8 UO  = 21
uint8 WSI = 26
uint8 WSO = 27
uint8 F   = 35
uint8 M   = 36
